### ISSUE TITLE
Units of measurement

### ISSUE THREAD

**Issue by ak-ustutt** [KoehnLab/chARpack#2]
I noticed that the distances using the measurement tool arr given in Ångström units. While this (non-SI) unit is still often used, this is confusing as our bonds (in the force-field setup) are given in pm. We should unify this.
Also, one sometimes may wish 3 digits after the decimal (in Å units, one after the decimal dot in pm).

To be discussed.

**Comment by tobiasrau** [comment]
Yes, a unification of all displayed units has to be done.
The Ångström units have been chosen since they are used in other tools like VMD and have been spotted during our user interviews.
We could implement an option in the settings to switch units so that the user can set a preference.

I'm not so sure if the same is true for the digits after the decimal.
We could simply increase the digits to 3.
